### ISSUE TITLE
README fixes 

### ISSUE THREAD

**Issue by Robbiekruszynski** [ciberexplosion/NFT-Auction-Marketplace#2]
Install commands do not cover a fresh clone of your REPO 

`npm i `

is needed before

`npm run start `

If I may suggest putting time into the README to walk a newcomer into your project from start to finish. This is beneficial to help devs who may way to contribute along with newcomers who want to see what your dApp is about without live deployment links.

**Comment by ciberexplosion** [comment]
Ok. working on it. Will add a gitignore as well.
